### ISSUE TITLE
Nejde stáhnout mkgmap prepare scriptem

### ISSUE THREAD

**Issue by pschonmann** [VasaMM/OSM-Garmin-Maps-by-VasaM#12]
Script si nestahuje/parsuje aktualni verzi mkgmap do souboru versions a pak nestahne soubor primo z webu, chyba 404

```d:\openstreetmap\OSM-Garmin-Maps-by-VasaM>prepare.py
The name of the output folder with garmin maps (default maps): OUTPUT
The name of the folder for map data download (default pbf): MAP_DATA_DOWNLOAD
The name of the folder for polygons (default polygons): POLYGONS
The name of the folder for height data (default hgt): HGT
The name of the folder for temporary data (default temp): TEMP
The name of the folder for sea data (default sea): SEA
The name of the folder for bounds data (default bounds): BOUNDS
Stahuji 'http://osm.thkukuk.de/data/sea-latest.zip'   239 MB
100%  [==============================]  239 MB / 239 MB   0 MB/s   eta 0
Stahuji 'http://osm.thkukuk.de/data/bounds-latest.zip'   1151 MB
100%  [==============================]  1151 MB / 1151 MB   0 MB/s   eta 0
Download splitter version 597
Stahuji 'https://www.mkgmap.org.uk/download/splitter-r597.zip'   1 MB
100%  [==============================]  1 MB / 1 MB   0 MB/s   eta 0
Unzip
Download mkgmap version 4565
Traceback (most recent call last):
  File "D:\openstreetmap\OSM-Garmin-Maps-by-VasaM\prepare.py", line 89, in <module>
    prepare()
  File "D:\openstreetmap\OSM-Garmin-Maps-by-VasaM\prepare.py", line 83, in prepare
    u.update()
  File "D:\openstreetmap\OSM-Garmin-Maps-by-VasaM\update.py", line 26, in update
    d.download('https://www.mkgmap.org.uk/download/mkgmap-r' + str(versions['mkgmap']) + '.zip', './mkgmap.zip')
  File "D:\openstreetmap\OSM-Garmin-Maps-by-VasaM\makerfuncs\download.py", line 48, in download
    response = urllib.request.urlopen(url)
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND```

**Comment by JanC** [comment]
dobry den,
taky mi to nejde. Je to tim ze verze `splitter` a `mkgmap` uz nejsou dostupné. Staci zmenit verse na

```
{"splitter": 602,"mkgmap": 4705}
```
v souboru  [versions.info](https://github.com/VasaMM/OSM-Garmin-Maps-by-VasaM/blob/master/versions.info)

**Comment by VasaMM** [comment]
Vyřešeno, nově by skript měl i hlásit smysluplnější chybu.
