### ISSUE TITLE
FileNotFoundError: [WinError 2] Systém nemůže nalézt uvedený soubor: 'hgt\\viewfinderHgtIndex_3.txt'

### ISSUE THREAD

**Issue by pschonmann** [VasaMM/OSM-Garmin-Maps-by-VasaM#2]
Zkusil jsem si nainstalovat podle návodu na Windows 10, ale vždycky končím na chybě viz níže.
Instalován opravený phyghtmap.

``` d:\openstreetmap\OSM-Garmin-Maps-by-VasaM-master>makeMap.py
Spusteno v 2019-06-18 18:10:36.911919
Zadejte zkratku statu, pro ktery chcete vytvorit mapu.
  * [OL] - Olomouc
  * [CZ] - Ceska republika
  * [SK] - Slovenska republika
  * [PL] - Polsko
  * [DE] - Nemecko
  * [AT] - Rakousko
  * [UA] - Ukrajina
  * [RO] - Rumunsko
  * [HR] - Chorvatsko
  * [NO] - Norsko
  * [DK] - Dansko
  * [SI] - Slovinsko
  * [GR] - Recko
  * [HU] - Madarsko
  * [ES] - Spanelsko
  * [IT] - Italie
  * [NL] - Nizozemsko
  * [KG] - Kyrgyzstan
  * [KZ] - Kazachstan
  * [NP] - Nepal
  * [MA] - Maroko
  * [TJ] - Tadzikistan
  * [NY] - New York
  * [VN] - Vietnam
  * [IR] - Iran
  * [IR_en] - Iran - en
Vybrana mapa: CZ
state: CZ
data id: CZ
Stahuji aktualni data
Stahuji 'http://download.geofabrik.de/europe/czech-republic-latest.osm.pbf'   694 MB
[K100%  [==============================]  694 MB / 694 MB   0 MB/s   eta 0
Generuji vrstevnice
checking if area N48E012 intersects with polygon ... no
checking if area N51E012 intersects with polygon ... no
checking if area N51E013 intersects with polygon ... no
checking if area N49E014 intersects with polygon ... yes
checking if area N49E016 intersects with polygon ... yes
checking if area N51E016 intersects with polygon ... no
checking if area N51E017 intersects with polygon ... no
checking if area N48E018 intersects with polygon ... no
checking if area N51E018 intersects with polygon ... no
N49E012: trying view3 ...
Traceback (most recent call last):
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\site-packages\phyghtmap-2.21-py3.7.egg\phyghtmap\NASASRTMUtil.py", line 544, in getViewUrl
FileNotFoundError: [WinError 2] Systém nemůže nalézt uvedený soubor: 'hgt\\viewfinderHgtIndex_3.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\Scripts\phyghtmap-script.py", line 11, in <module>
    load_entry_point('phyghtmap==2.21', 'console_scripts', 'phyghtmap')()
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\site-packages\phyghtmap-2.21-py3.7.egg\phyghtmap\main.py", line 670, in main
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\site-packages\phyghtmap-2.21-py3.7.egg\phyghtmap\NASASRTMUtil.py", line 790, in getFiles
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\site-packages\phyghtmap-2.21-py3.7.egg\phyghtmap\NASASRTMUtil.py", line 776, in getFile
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\site-packages\phyghtmap-2.21-py3.7.egg\phyghtmap\NASASRTMUtil.py", line 546, in getViewUrl
  File "C:\Users\Petr\AppData\Local\Programs\Python\Python37\lib\site-packages\phyghtmap-2.21-py3.7.egg\phyghtmap\NASASRTMUtil.py", line 421, in makeViewHgtIndex
  File "C:\Users\Petr\AppData\Roaming\Python\Python37\site-packages\bs4\__init__.py", line 196, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
Traceback (most recent call last):
  File "D:\openstreetmap\OSM-Garmin-Maps-by-VasaM-master\makeMap.py", line 367, in <module>
    main()
  File "D:\openstreetmap\OSM-Garmin-Maps-by-VasaM-master\makeMap.py", line 167, in main
    os.rename( glob.glob( './pbf/' + state.data_id + '-SRTM*.osm.pbf' )[0], './pbf/' + state.data_id + '-SRTM.osm.pbf' )
IndexError: list index out of range ```

**Comment by VasaMM** [comment]
Na vině je antivir z windows 10 - konkrétně ochrana proti ransomware. Možná řešení:
1) Úplné vypnutí ochrany **NEDOPORUČUJI**
2) Přidat výjimku pro python.exe
3) Vyjmout složku s mapami z ochrany

Návod pro vypnutí [zde](https://support.microsoft.com/cs-cz/help/4046851/windows-10-allow-blocked-app-windows-security). Výjimka pro python či danou složku se udělá obdobně.

**Comment by pschonmann** [comment]
Zkoušel jsem podle návodu vypnout, ale stále stejná chyba.

**Comment by QuoXcz** [comment]
Ahoj, na win10 jsem také neuspěl. Dneska jsem neuspěl ani na win7. V podstatě ta samá chyba. Na linuxu bez problémů. Tuší někdo jak to na win7 opravit? Díky

**Comment by QuoXcz** [comment]
Vypadá to, že problém je vyřešen. na win 7, teď jsem to rozchodil i na 64bit win10. Udělal jsem tento krok navíc: cmd -> pip install lxml

**Comment by pschonmann** [comment]
Potvrzuji funkčnost s nainstalovaným lxml
